### ISSUE TITLE
ログインしていない場合ログインページへ移行させる

### ISSUE THREAD

**Issue by yi01** [yi01/dive_into_code#10]

**Comment by norotime** [comment]
@yi01 こんなふうにチェックリストの作成をすると、進捗を自分でチェックできて便利ですよ！
こう書くと・・・
```
- [ ] a task list item
- [ ] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
```
↓
こうなる
↓
- [ ] a task list item
- [x] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed

**Comment by yi01** [comment]
scaffoldで完了
